# Netlify Configuration for Frontend
[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_BACKEND_URL = "https://globalvoice-backend.onrender.com"
  VITE_WS_URL = "wss://globalvoice-backend.onrender.com"

[context.deploy-preview.environment]
  VITE_BACKEND_URL = "https://globalvoice-backend.onrender.com"
  VITE_WS_URL = "wss://globalvoice-backend.onrender.com"

# Note: Update these URLs after deploying backend to Render
