# Fly.io Configuration for GlobalVoice Nexus Backend
# World-class multi-region deployment

app = "globalvoice-backend"
primary_region = "iad" # US East (Ashburn, VA)

[build]
  [build.args]
    NODE_VERSION = "20"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

# Multi-region deployment for global low latency
[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

# Health checks
[[services.tcp_checks]]
  grace_period = "10s"
  interval = "30s"
  restart_limit = 0
  timeout = "5s"

[[services.http_checks]]
  interval = "30s"
  grace_period = "10s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "5s"
  tls_skip_verify = false

# VM Resources
[vm]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

# Auto-scaling configuration
[metrics]
  port = 9091
  path = "/metrics"

# Deploy to multiple regions for global coverage
# Primary: US East (iad)
# Secondary regions will be added after initial deployment
