# Fly.io Configuration for GlobalVoice Nexus Backend
# World-class multi-region deployment

app = "globalvoice-backend"
primary_region = "iad" # US East (Ashburn, VA)

[build]
  [build.args]
    NODE_VERSION = "20"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

# VM Resources
[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

# Deploy to multiple regions for global coverage
# Primary: US East (iad)
# Secondary regions will be added after initial deployment
